### ISSUE TITLE
crash on delete of todo item

### ISSUE THREAD

**Issue by gedw99** [fjl/gio-demos#3]
Hey

Nice demo !! 

Just wanted to let you know there is a crash when deleting a todo item..

**Comment by gedw99** [comment]
OK its a schema evolution bug.

I had an old events in the store and the code had changed, so it went nuts.

Use CBOR or Proto to avoid this bug.

**Comment by fjl** [comment]
Are you using the app!?

**Comment by fjl** [comment]
Can you report the panic message please?

**Comment by gedw99** [comment]
sorry but i cant recreate it because i killed the store. Sorry dude... 

https://github.com/thiagozs/go-nats-workers/blob/main/models/models.go shows how to use CBOR which will fix the probl,e i think.

**Comment by gedw99** [comment]
> Are you using the app!?

Yes mac

**Comment by fjl** [comment]
I poked around a bit, and did find a crash when removing an item while editing it.

In general, the event processing logic is not robust against bad data or any inconsistencies introduced by faults in the
UI. I want to implement pruning of the event store at some point, and then certain invariants could also be checked.

**Comment by gedw99** [comment]
ah just saw the fix

``` m.items[it.id] == nil ```

so i was wrong, and it was a race condition ?

**Comment by gedw99** [comment]
It crashed on delete while editing like you suspected.

So sounds like a race condition pattern. 


thanks for fixing it so fast. Its nice code that i just wanted to learn patterns of currency from.
